name: fontify
version: 0.3.0-nullsafety.1
description: >-
  Converts SVG icons to OTF font and generates Flutter-compatible class.
  Provides an API and a CLI tool.
homepage: https://github.com/westracer/fontify

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.7.0
  collection: ^1.18.0
  logger: ^2.5.0
  meta: ^1.15.0
  path: ^1.9.0
  path_parsing: ^1.1.0
  recase: ^4.1.0
  vector_math: ^2.1.4
  xml: ^6.5.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  
executables:
  fontify: fontify