name: fontify
version: 0.3.0-nullsafety.1
description: >-
  Converts SVG icons to OTF font and generates Flutter-compatible class.
  Provides an API and a CLI tool.
homepage: https://github.com/westracer/fontify

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.5.0
  collection: ^1.17.2
  logger: ^2.2.0
  meta: ^1.11.0
  path: ^1.9.0
  path_parsing: ^1.0.1
  recase: ^4.1.0
  vector_math: ^2.1.4
  xml: ^6.5.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.4
  
executables:
  fontify: fontify