name: fontify
version: 0.3.0-nullsafety.1
description: >-
  Converts SVG icons to OTF font and generates Flutter-compatible class.
  Provides an API and a CLI tool.
homepage: https://github.com/westracer/fontify

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.1
  collection: ^1.16.0
  logger: ^1.1.0
  meta: ^1.7.0
  path: ^1.8.1
  path_parsing: ^1.0.0
  recase: ^4.0.0
  vector_math: ^2.1.2
  xml: ^6.0.1
  yaml: ^3.1.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.0
  
executables:
  fontify: fontify